import { cva } from "class-variance-authority";

import {
  Article,
  ArrowClockwise,
  ArrowSquareOut,
  ArrowUDownLeft,
  ArrowsHorizontal,
  ArrowsMerge,
  ArrowsVertical,
  CaretCircleUpDown,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUpDown,
  ChatCircleDots,
  Check,
  CheckSquare,
  ClipboardText,
  CloudArrowDown,
  Code,
  Columns,
  Copy,
  DotsSixVertical,
  Eye,
  FileCode,
  FileText,
  FilmStrip,
  Gear,
  Highlighter,
  Keyboard,
  Laptop,
  Link,
  LinkBreak,
  LinkSimpleBreak,
  ListDashes,
  ListNumbers,
  MagnifyingGlass,
  Minus,
  Moon,
  PaintBucket,
  Paperclip,
  Paragraph,
  Pen,
  PencilRuler,
  PencilSimpleLine,
  Plus,
  Quotes,
  Rectangle,
  Rows,
  SlidersHorizontal,
  Smiley,
  Spinner,
  Sun,
  Table,
  TextAUnderline,
  TextAlignCenter,
  TextAlignJustify,
  TextAlignLeft,
  TextAlignRight,
  TextB,
  TextHFive,
  TextHFour,
  TextHOne,
  TextHSix,
  TextHThree,
  TextHTwo,
  TextIndent,
  TextItalic,
  TextOutdent,
  TextStrikethrough,
  TextSubscript,
  TextSuperscript,
  TextUnderline,
  Trash,
  X,
  XCircle,
  Image,
} from "@phosphor-icons/react";

export const Icons = {
  add: Plus,
  alignCenter: TextAlignCenter,
  alignJustify: TextAlignJustify,
  alignLeft: TextAlignLeft,
  alignRight: TextAlignRight,
  arrowDown: CaretDown,
  arrowRight: CaretRight,
  attachment: Paperclip,
  bg: PaintBucket,
  blockquote: Quotes,
  bold: TextB,
  check: Check,
  chevronDown: CaretDown,
  chevronLeft: CaretLeft,
  chevronRight: CaretRight,
  chevronsUpDown: CaretUpDown,
  clear: X,
  close: XCircle,
  code: Code,
  codeblock: FileCode,
  color: TextAUnderline,
  column: Rectangle,
  combine: ArrowsMerge,
  comment: ChatCircleDots,
  commentAdd: Plus,
  conflict: LinkBreak,
  copy: Copy,
  copyDone: ClipboardText,
  delete: Trash,
  dependency: Link,
  doubleColumn: Columns,
  downloadCloud: CloudArrowDown,
  dragHandle: DotsSixVertical,
  editing: Pen,
  ellipsis: CaretCircleUpDown,
  embed: FilmStrip,
  emoji: Smiley,
  excalidraw: PencilRuler,
  externalLink: ArrowSquareOut,
  h1: TextHOne,
  h2: TextHTwo,
  h3: TextHThree,
  h4: TextHFour,
  h5: TextHFive,
  h6: TextHSix,
  highlight: Highlighter,
  hr: Minus,
  image: Image,
  indent: TextIndent,
  italic: TextItalic,
  kbd: Keyboard,
  laptop: Laptop,
  lineHeight: ArrowUDownLeft,
  link: Link,
  media: Image,
  minus: Minus,
  moon: Moon,
  more: ArrowsHorizontal,
  moreVertical: ArrowsVertical,
  ol: ListNumbers,
  outdent: TextOutdent,
  page: FileText,
  paragraph: Paragraph,
  plugin: SlidersHorizontal,
  pragma: Link,
  refresh: ArrowClockwise,
  row: Rows,
  search: MagnifyingGlass,
  settings: Gear,
  spinner: Spinner,
  strikethrough: TextStrikethrough,
  subscript: TextSubscript,
  suggesting: PencilSimpleLine,
  sun: Sun,
  superscript: TextSuperscript,
  table: Table,
  text: Article,
  todo: CheckSquare,
  trash: Trash,
  ul: ListDashes,
  underline: TextUnderline,
  unlink: LinkSimpleBreak,
  viewing: Eye,
};

export const iconVariants = cva("", {
  defaultVariants: {},
  variants: {
    size: {
      md: "mr-2 size-6",
      sm: "mr-2 size-4",
    },
    variant: {
      menuItem: "mr-2 size-5",
      toolbar: "size-5",
    },
  },
});
